# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C1_2_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

# Modified from Smay's code for HW9

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CircuitStructuralDesign(object):
    def setupUi(self, CircuitStructuralDesign):
        CircuitStructuralDesign.setObjectName("CircuitStructuralDesign")
        CircuitStructuralDesign.resize(1060, 1161)
        self.verticalLayout = QtWidgets.QVBoxLayout(CircuitStructuralDesign)
        self.verticalLayout.setObjectName("verticalLayout")
        self.grp_Load = QtWidgets.QGroupBox(CircuitStructuralDesign)
        self.grp_Load.setObjectName("grp_Load")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.grp_Load)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_Open = QtWidgets.QPushButton(self.grp_Load)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_Open.sizePolicy().hasHeightForWidth())
        self.btn_Open.setSizePolicy(sizePolicy)
        self.btn_Open.setObjectName("btn_Open")
        self.horizontalLayout.addWidget(self.btn_Open, 0, QtCore.Qt.AlignTop)
        self.te_Path = QtWidgets.QTextEdit(self.grp_Load)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.te_Path.sizePolicy().hasHeightForWidth())
        self.te_Path.setSizePolicy(sizePolicy)
        self.te_Path.setMinimumSize(QtCore.QSize(700, 50))
        self.te_Path.setMaximumSize(QtCore.QSize(1000, 100))
        self.te_Path.setBaseSize(QtCore.QSize(500, 0))
        self.te_Path.setObjectName("te_Path")
        self.horizontalLayout.addWidget(self.te_Path)
        self.verticalLayout.addWidget(self.grp_Load)
        self.grp_DesignReport = QtWidgets.QGroupBox(CircuitStructuralDesign)
        self.grp_DesignReport.setObjectName("grp_DesignReport")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.grp_DesignReport)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.te_DesignReport = QtWidgets.QTextEdit(self.grp_DesignReport)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.te_DesignReport.sizePolicy().hasHeightForWidth())
        self.te_DesignReport.setSizePolicy(sizePolicy)
        self.te_DesignReport.setMinimumSize(QtCore.QSize(300, 300))
        self.te_DesignReport.setMaximumSize(QtCore.QSize(1000, 700))
        self.te_DesignReport.setObjectName("te_DesignReport")
        self.horizontalLayout_2.addWidget(self.te_DesignReport)
        self.verticalLayout.addWidget(self.grp_DesignReport)
        self.gv_Main = QtWidgets.QGraphicsView(CircuitStructuralDesign)
        self.gv_Main.setObjectName("gv_Main")
        self.verticalLayout.addWidget(self.gv_Main)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lbl_MousePos = QtWidgets.QLabel(CircuitStructuralDesign)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_MousePos.sizePolicy().hasHeightForWidth())
        self.lbl_MousePos.setSizePolicy(sizePolicy)
        self.lbl_MousePos.setMinimumSize(QtCore.QSize(500, 0))
        self.lbl_MousePos.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.lbl_MousePos.setObjectName("lbl_MousePos")
        self.horizontalLayout_3.addWidget(self.lbl_MousePos, 0, QtCore.Qt.AlignLeft)
        self.lbl_Zoom = QtWidgets.QLabel(CircuitStructuralDesign)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_Zoom.sizePolicy().hasHeightForWidth())
        self.lbl_Zoom.setSizePolicy(sizePolicy)
        self.lbl_Zoom.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_Zoom.setObjectName("lbl_Zoom")
        self.horizontalLayout_3.addWidget(self.lbl_Zoom)
        self.spnd_Zoom = QtWidgets.QDoubleSpinBox(CircuitStructuralDesign)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spnd_Zoom.sizePolicy().hasHeightForWidth())
        self.spnd_Zoom.setSizePolicy(sizePolicy)
        self.spnd_Zoom.setMinimum(0.25)
        self.spnd_Zoom.setMaximum(10.0)
        self.spnd_Zoom.setSingleStep(0.25)
        self.spnd_Zoom.setObjectName("spnd_Zoom")
        self.horizontalLayout_3.addWidget(self.spnd_Zoom)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(CircuitStructuralDesign)
        QtCore.QMetaObject.connectSlotsByName(CircuitStructuralDesign)

    def retranslateUi(self, CircuitStructuralDesign):
        _translate = QtCore.QCoreApplication.translate
        CircuitStructuralDesign.setWindowTitle(_translate("CircuitStructuralDesign", "Circuit Design"))
        self.grp_Load.setTitle(_translate("CircuitStructuralDesign", "Circuit File and Load Set"))
        self.btn_Open.setText(_translate("CircuitStructuralDesign", "Open and Read a Circuit File"))
        self.grp_DesignReport.setTitle(_translate("CircuitStructuralDesign", "Circuit Report"))
        self.lbl_MousePos.setText(_translate("CircuitStructuralDesign", "TextLabel"))
        self.lbl_Zoom.setText(_translate("CircuitStructuralDesign", "Zoom"))

